Repository snowhite-hyu/frontend, pull requests merged in 2025-04, with the labels that each got.

#1 [docs] commit template 작성
  .gitmessage
Labels: documentation

#2 [docs] 파일 확장자 변경
  .gitmessage.txt
Labels: documentation

#8 로그인 페이지 예제 및 API 예제
  bun.lock
  components.json
  package.json
  src/App.tsx
  src/apis/common/ApiClient.ts
  src/apis/common/Login.ts
  src/apis/common/RestClient.ts
  src/components/common/Background.tsx
  src/components/layer/HealthyLayer.tsx
  src/components/layer/LoadingLayer.tsx
  src/components/ui/AuthCard.tsx
  src/components/ui/LoadingUI.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/input.tsx
  src/components/ui/sonner.tsx
  src/index.css
  src/lib/utils.ts
  src/main.tsx
  src/models/common/Login.ts
  src/models/common/RestModel.ts
  src/models/common/User.ts
  src/pages/Login.tsx
  src/pages/Welcome.tsx
  src/routes.tsx
  src/stores/common/HealthyStore.ts
  src/stores/common/LoadingStore.ts
  src/stores/common/SessionStore.ts
  vite.config.ts
Labels: good first issue

#9 Lint && Separate Api service and Asset service.
  src/apis/common/ApiClient.ts
  src/apis/common/Login.ts
  src/apis/common/RestClient.ts
  src/components/layer/HealthyLayer.tsx
  src/components/layer/LoadingLayer.tsx
  src/components/ui/AuthCard.tsx
  src/pages/Login.tsx
Labels: bug

#10 Fix missing env
  .env.build
  .env.dev
  src/apis/common/ApiClient.ts
Labels: bug
