Repository snowhite-hyu/frontend, pull requests merged in 2025-06, with the labels that each got.

#27 [SH-61] 매뉴얼 UI 구현
  src/assets/manual/manual1.svg
  src/assets/manual/manual2.svg
  src/assets/manual/manual3.svg
  src/assets/manual/manual4.svg
  src/assets/nextIcon.svg
  src/assets/prevIcon.svg
  src/components/ui/dialog/Dialog.tsx
  src/components/ui/dialog/GameEndDialog.tsx
  src/components/ui/dialog/ManualDialog.tsx
  src/components/ui/dialog/RoundEndDialog.tsx
  src/pages/Main.tsx
  src/pages/TestDialog.tsx
Labels: enhancement

#30 [SH-170] 게임 화면 내에 카드 배치 기능 구현
  src/components/game/DroppableCell.tsx
  src/components/game/Map.tsx
  src/pages/Game.tsx
  src/pages/TestPage.tsx
Labels: enhancement

#29 [SH-156] 방 관련 비즈니스 로직 구현
  .env.build
  .env.dev
  package-lock.json
  package.json
  src/apis/common/Room.ts
  src/hooks/useLogin.ts
  src/hooks/useRoom.ts
  src/models/common/Room.d.ts
  src/models/common/User.d.ts
  src/pages/CreateRoom.tsx
  src/pages/RoomList.tsx
  src/pages/Waiting.tsx
  src/sockets/BaseSocket.ts
  src/sockets/RoomSocket.ts
  src/stores/common/RoomInfoState.ts
  src/stores/common/RoomSocketStore.ts
Labels: enhancement

#32 SH-175 채팅 기능 구현
  src/models/common/Room.d.ts
  src/pages/Waiting.tsx
  src/sockets/RoomSocket.ts
  src/stores/common/RoomInfoState.ts
Labels: enhancement

#31 [SH-153, SH-169] FE 게임 구현
  components.json
  src/apis/common/ApiClient.ts
  src/apis/common/RestClient.ts
  src/components/asset/ActionCard.tsx
  src/components/asset/Card.tsx
  src/components/asset/GoalCard.tsx
  src/components/asset/RouteCard.tsx
  src/components/game/DroppableCell.tsx
  src/components/ui/PlayerPanel.tsx
  src/components/ui/dialog/Dialog.tsx
  src/components/ui/dialog/GameEndDialog.tsx
  src/components/ui/dialog/RoundEndDialog.tsx
  src/generated/model.d.ts
  src/hooks/useGame.ts
  src/hooks/useLogin.ts
  src/models/common/Payload.d.ts
  src/models/common/Room.d.ts
  src/models/common/User.d.ts
  src/models/game/Card.d.ts
  src/models/game/Game.d.ts
  src/models/game/Player.d.ts
  src/models/room/Room.d.ts
  src/pages/CreateRoom.tsx
  src/pages/Game.tsx
  src/pages/RoomList.tsx
  src/pages/TestDialog.tsx
  src/pages/TestPage.tsx
  src/pages/Waiting.tsx
  src/routes.tsx
  src/sockets/BaseSocket.ts
  src/sockets/RoomSocket.ts
  src/stores/common/RoomInfoState.ts
  src/stores/common/RoomSocketStore.ts
  src/stores/common/SessionStore.ts
  src/stores/common/SocketStore.ts
  src/stores/game/GameStore.ts
  src/vite-env.d.ts
Labels: enhancement

#35 [FEAT] 방장 퇴장 시 남아있는 잔여 플레이어 방 목록 페이지로 자동 라우팅
  src/pages/Waiting.tsx
  src/sockets/RoomSocket.ts
Labels: enhancement

#36 [SH-179] 필드 정보 변경 대응
  src/components/asset/GoalCard.tsx
  src/components/asset/RouteCard.tsx
  src/components/game/DroppableCell.tsx
  src/components/ui/PlayerPanel.tsx
  src/components/ui/dialog/Dialog.tsx
  src/components/ui/dialog/GameEndDialog.tsx
  src/components/ui/dialog/ManualDialog.tsx
  src/components/ui/dialog/RoundEndDialog.tsx
  src/hooks/useGame.ts
  src/models/game/Game.d.ts
  src/pages/CreateRoom.tsx
  src/pages/Game.tsx
  src/pages/Main.tsx
  src/pages/Register.tsx
  src/pages/RoomList.tsx
  src/pages/Waiting.tsx
  src/sockets/RoomSocket.ts
  src/stores/common/RoomInfoState.ts
  src/stores/common/RoomSocketStore.ts
  src/stores/game/GameStore.ts
Labels: enhancement

#38 매뉴얼 확대 기능 추가
  src/components/ui/dialog/ManualDialog.tsx
Labels: enhancement

#42 [SH-203] 맵 카드 사용 및 렌더링 추가
  src/hooks/useGame.ts
  src/pages/Game.tsx
Labels: 🐛bug

#44 [SH-205] 게임 종료 구현
  src/hooks/useGame.ts
  src/models/game/Game.d.ts
  src/pages/Game.tsx
Labels: ✨enhancement

#45 두가지 액션 허용
  src/pages/Game.tsx
Labels: 🐛bug
